Connected Elderly dashboard to database and changed some things in MealManager and localizations
M-AboWarda/AgeWell-Meals pull request #44
Opened 2023-10-16 11:06 UTC by JuhoP02

2023-10-16 14:08 UTC, Mnpn approved these changes
LGTM

2023-10-17 16:55 UTC, nouradeen requested changes
- Adding meals from the caregiver side still does not add meals inside a collection inside the elderly account itself. I don't see why right now, you are calling `userCollection.doc(uid).collection('meals')` which is supposed to add the meals to that location. I can see what I can find.
- In the `MealManager.dart`, I see you are trying to access the meals inside the "elderly" account, through a collection inside of the document. But it is returning no data because of the 
```dart
if (!mealSnapshot.hasData)
{...}
```
So my suggestion now is not to merge the code until I find out the problem.

2023-10-17 17:13 UTC, JuhoP02 commented
Weird, for me it seems to be working correctly. Remember that the meal editor adds meals for 'tomorrow', and the elderly dashboard returns meals for 'today'.

2023-10-17 17:19 UTC, nouradeen commented
Can you try to commit and push your code once again?
I'll try to pull it and test it.

2023-10-17 17:35 UTC, JuhoP02 commented
The elderly dashboard uses getRemainingMealsForDate, which returns the meals for the date, but also checks which meals are after the current time of day. So you might have to change the time too

2023-10-17 18:42 UTC, JuhoP02 commented
I added an offset to the timing that can be changed. I think Mohammad is working on the counter logic so I have not touched that.

2023-10-18 16:49 UTC, nouradeen commented on lib/pages/elderly/meal_confirmation.dart
>                              onTap: () {},
- Remove `GestureDetector()`, we had this just for testing the miss screens

2023-10-18 16:51 UTC, nouradeen commented on lib/pages/elderly/meal_confirmation.dart
> +                                    var nextMealData = mealDocs[0].data();
`mealDocs[0]` is not always the next meal right?, if we have already 3 meals in the database, mealDocs[0] will grab the last one based on the time, beacause they are sorted in the database.

2023-10-18 16:52 UTC, nouradeen commented on lib/pages/elderly/meal_confirmation.dart
> +                      var nextMealData = mealDocs[0].data();
Same thing here

2023-10-18 16:53 UTC, nouradeen requested changes
Fix the comments. I have not tested the code, but I did the same error once before 😃

2023-10-18 16:54 UTC, nouradeen commented on lib/pages/elderly/meal_confirmation.dart
> +                                    var nextMealData = mealDocs[0].data();
(First one in the list "in the database")

2023-10-18 17:15 UTC, JuhoP02 commented
The database should return the meals in ascending order based on the date (lowest/earliest = first in list), so it should return the first one.

2023-10-18 17:32 UTC, JuhoP02 commented
It is set to mealDocs[0] in meal_confirmation because the 'currentmeal' status gets set from 'Waiting' to 'Done'. Because of that the [0] is the next meal in that screen. Is that what you meant?

2023-10-18 18:07 UTC, merged